# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClusterConfigEndpPointAccessTypeEnum(object):

    """Implementation of the 'ClusterConfigEndpPointAccessType' enum.

    TODO: type enum description here.

    Attributes:
        PRIVATEACCESS: TODO: type description here.
        PRIVATEPUBLICACCESS: TODO: type description here.
        PUBLICACCESS: TODO: type description here.

    """

    PRIVATEACCESS = 'privateAccess'

    PRIVATEPUBLICACCESS = 'privatePublicAccess'

    PUBLICACCESS = 'publicAccess'
