# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from verizon.api_helper import APIHelper
from verizon.configuration import Server
from verizon.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from verizon.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from apimatic_core.authentication.multiple.and_auth_group import And
from apimatic_core.authentication.multiple.or_auth_group import Or
from verizon.models.request_result import RequestResult
from verizon.models.connection_history_result import ConnectionHistoryResult
from verizon.models.device_provisioning_history_list_result import DeviceProvisioningHistoryListResult
from verizon.models.add_devices_result import AddDevicesResult
from verizon.models.delete_devices_result import DeleteDevicesResult
from verizon.models.account_device_list_result import AccountDeviceListResult
from verizon.models.device_usage_list_result import DeviceUsageListResult
from verizon.models.device_mismatch_list_result import DeviceMismatchListResult
from verizon.models.device_extended_diagnostics_result import DeviceExtendedDiagnosticsResult
from verizon.exceptions.connectivity_management_result_exception import ConnectivityManagementResultException


class DeviceManagementController(BaseController):

    """A Controller to access Endpoints in the verizon API."""
    def __init__(self, config):
        super(DeviceManagementController, self).__init__(config)

    def change_devices_service_plan(self,
                                    body):
        """Does a PUT request to /devices/actions/plan.

        Changes the service plan for one or more devices.

        Args:
            body (ServicePlanUpdateRequest): Change service plan request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/plan')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def suspend_service_for_devices(self,
                                    body):
        """Does a POST request to /devices/actions/suspend.

        Suspends service for one or more devices.

        Args:
            body (CarrierActionsRequest): Suspend request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/suspend')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def restore_service_for_suspended_devices(self,
                                              body):
        """Does a POST request to /devices/actions/restore.

        Restores service to one or more suspended devices.

        Args:
            body (CarrierActionsRequest): Restore request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/restore')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def check_devices_availability_for_activation(self,
                                                  body):
        """Does a POST request to /devices/availability/actions/list.

        Checks whether specified devices are registered by the manufacturer
        with the Verizon network and are available to be activated.

        Args:
            body (DeviceRequest): Device Query

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/availability/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def update_device_id(self,
                         service_type,
                         body):
        """Does a PUT request to /devices/{serviceType}/actions/deviceId.

        Changes the identifier of a 3G or 4G device to match hardware changes
        made for a line of service. Use this request to transfer the line of
        service and the MDN to new hardware, or to change the MDN.

        Args:
            service_type (string): Identifier type
            body (ChangeDeviceIdRequest): Device query

        Returns:
            RequestResult: Response from the API. A unique string that
                associates the request with the results that are sent via a
                callback service.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/{serviceType}/actions/deviceId')
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                            .key('serviceType')
                            .value(service_type)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def activate_service_for_devices(self,
                                     body):
        """Does a POST request to /devices/actions/activate.

        If the devices do not already exist in the account, this API resource
        adds them before activation.

        Args:
            body (CarrierActivateRequest): Activate request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/activate')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def update_devices_contact_information(self,
                                           body):
        """Does a PUT request to /devices/actions/contactinfo.

        Sends a CarrierService callback message for each device in the request
        when the contact information has been changed, or if there was a
        problem and the change could not be completed.

        Args:
            body (ContactInfoUpdateRequest): Change contact info request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/contactinfo')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def retrieve_device_connection_history(self,
                                           body):
        """Does a POST request to /devices/connections/actions/listHistory.

        Each response includes a maximum of 500 records. To obtain more
        records, you can call the API multiple times, adjusting the earliest
        value each time to start where the previous request finished.

        Args:
            body (DeviceConnectionListRequest): Device connection query

        Returns:
            ConnectionHistoryResult: Response from the API. List of device
                connection events, sorted by the occurredAt timestamp, oldest
                first.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/connections/actions/listHistory')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ConnectionHistoryResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def list_devices_provisioning_history(self,
                                          body):
        """Does a POST request to /devices/history/actions/list.

        Returns the provisioning history of a specified device during a
        specified time period.

        Args:
            body (DeviceProvisioningHistoryListRequest): Device provisioning
                history query

        Returns:
            list of DeviceProvisioningHistoryListResult: Response from the
                API. List of Device Provision History events, sorted by the
                timestamp, oldest first.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/history/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DeviceProvisioningHistoryListResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def add_devices(self,
                    body):
        """Does a POST request to /devices/actions/add.

        Use this API if you want to manage some device settings before you are
        ready to activate service for the devices.

        Args:
            body (AddDevicesRequest): Devices to Add

        Returns:
            list of AddDevicesResult: Response from the API. For each device
                in the request, contains device identifiers and a success or
                failure response.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/add')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AddDevicesResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def deactivate_service_for_devices(self,
                                       body):
        """Does a POST request to /devices/actions/deactivate.

        Deactivating service for a device may result in an early termination
        fee (ETF) being charged to the account, depending on the terms of the
        contract with Verizon. If your contract allows ETF waivers and if you
        want to use one for a particular deactivation, set the etfWaiver value
        to True.

        Args:
            body (CarrierDeactivateRequest): Deactivate request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/deactivate')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def delete_deactivated_devices(self,
                                   body):
        """Does a POST request to /devices/actions/delete.

        Use this API to remove unneeded devices from an account

        Args:
            body (DeleteDevicesRequest): Devices to delete

        Returns:
            list of DeleteDevicesResult: Response from the API. For each
                device in the request, contains device identifiers and a
                success or failure response.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/delete')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DeleteDevicesResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def list_devices_information(self,
                                 body):
        """Does a POST request to /devices/actions/list.

        Returns information about a single device or information about all
        devices that match the given parameters. Returned information includes
        device provisioning state, service plan, MDN, MIN, and IP address.

        Args:
            body (AccountDeviceListRequest): Device Query

        Returns:
            AccountDeviceListResult: Response from the API. List of devices
                that match the request parameters, ordered by device creation
                date, oldest first.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AccountDeviceListResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def list_current_devices_prl_version(self,
                                         body):
        """Does a POST request to /devices/prl/actions/list.

        4G and GSM devices do not have a PRL.

        Args:
            body (DevicePrlListRequest): Device PRL query

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/prl/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def list_devices_usage_history(self,
                                   body):
        """Does a POST request to /devices/usage/actions/list.

        Returns the network data usage history of a device during a specified
        time period.

        Args:
            body (DeviceUsageListRequest): Device usage query

        Returns:
            DeviceUsageListResult: Response from the API. List of device usage
                events, sorted by the timestamp, oldest first.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/usage/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DeviceUsageListResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def update_devices_custom_fields(self,
                                     body):
        """Does a PUT request to /devices/actions/customFields.

        Sends a CarrierService callback message for each device in the request
        when the custom fields have been changed, or if there was a problem
        and the change could not be completed.

        Args:
            body (CustomFieldsUpdateRequest): Change custom fields request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/customFields')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def list_devices_with_imei_iccid_mismatch(self,
                                              body):
        """Does a POST request to /devices/actions/list/imeiiccidmismatch.

        Returns a list of all 4G devices with an ICCID (SIM) that was not
        activated with the expected IMEI (hardware) during a specified time
        frame.

        Args:
            body (DeviceMismatchListRequest): Device Query

        Returns:
            DeviceMismatchListResult: Response from the API. List of devices
                that have mismatched IMEIs and ICCIDs.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/list/imeiiccidmismatch')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DeviceMismatchListResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def move_devices_within_accounts_of_profile(self,
                                                body):
        """Does a PUT request to /devices/actions/move.

        Move active devices from one billing account to another within a
        customer profile.

        Args:
            body (MoveDeviceRequest): Move request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/move')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def update_devices_state(self,
                             body):
        """Does a PUT request to /devices/actions/gotostate.

        Changes the provisioning state of one or more devices to a specified
        customer-defined service and state.

        Args:
            body (GoToStateRequest): Move state request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/actions/gotostate')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def update_devices_cost_center_code(self,
                                        body):
        """Does a PUT request to /devices/costCenter.

        Changes or removes the CostCenterCode value or customer name and
        address (Primary Place of Use) for one or more devices.

        Args:
            body (DeviceCostCenterRequest): Change cost center request

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/costCenter')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def get_device_extended_diagnostic_information(self,
                                                   body):
        """Does a POST request to /devices/extendeddiagnostics/actions/list.

        Returns extended diagnostic information about a specified device,
        including connectivity, provisioning, billing and location status.

        Args:
            body (DeviceExtendedDiagnosticsRequest): Device Query

        Returns:
            DeviceExtendedDiagnosticsResult: Response from the API. Device
                diagnostic information

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/extendeddiagnostics/actions/list')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DeviceExtendedDiagnosticsResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def get_device_service_suspension_status(self,
                                             body):
        """Does a POST request to /devices/suspension/status.

        Returns DeviceSuspensionStatus callback messages containing the
        current device state and information on how many days a device has
        been suspended and can continue to be suspended.

        Args:
            body (DeviceSuspensionStatusRequest): Device query

        Returns:
            RequestResult: Response from the API. Request ID

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/suspension/status')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()

    def retrieve_aggregate_device_usage_history(self,
                                                body):
        """Does a POST request to /devices/usage/actions/list/aggregate.

        The information is returned in a callback response, so you must
        register a URL for DeviceUsage callback messages using the POST
        /callbacks API.

        Args:
            body (DeviceAggregateUsageListRequest): Aggregated usage request

        Returns:
            RequestResult: Response from the API. A unique string that
                associates the request with the results that are sent via a
                callback service.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT1)
            .path('/devices/usage/actions/list/aggregate')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('global'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RequestResult.from_dictionary)
            .local_error('400', 'Error Response', ConnectivityManagementResultException)
        ).execute()
